### ISSUE TITLE
Constant name tokenization fails for names with multiple digits and underscores

### ISSUE THREAD

**Issue by smelfungus** [notKamui/Keval#48]
Hello! Thank you for that fantastic library.
It seems like `TOKENIZER_REGEX` fails to tokenize constants with names like `AB_ABCD5_Abc2_Abc_Abc_A1` and `P_331abcf98a8105826357ea87c1a7e456` properly, resulting in `Invalid expression at position...` exceptions.

**Comment by notKamui** [comment]
Hi ! Thank you for bringing this bug to my attention.
This is unfortunate. 

I'll take a look as soon as possible to fix this. 
If you wish to contribute though, you can do so by creating a PR.

**Comment by smelfungus** [comment]
I’ve put together a fix for this issue in #49. Thanks a lot in advance for checking it out and sharing any thoughts or feedback.
Cheers!

**Comment by notKamui** [comment]
@smelfungus Thanks a lot for your contribution man ! I've checked your PR, seems all good.
I should have simplified that regex since the last big rework

**Comment by notKamui** [comment]
Will publish the patch as soon as possible (should be up in half a day). Closing this issue
