### ISSUE TITLE
PI to π

### ISSUE THREAD

**Issue by sosauce** [notKamui/Keval#52]
Hi it's me again 😁

If I'm not mistaken, as of now PI must be sent to te evaluator as "PI", it'd be cool if it could be "π", I already tried using .replace() but I got an issue when deleting once would result to "P" (see CuteCalc issues)

**Comment by SlamaFR** [comment]
You might just want to replace "π" by "PI" when passing the string to evaluate to Keval. This way, you can handle π as a normal char on your side.

**Comment by sosauce** [comment]
Oops yes ur right, didnt think of it 😅
